version: '3.8'
#containers => services
services:
  mysql-springboot-container:
    image: mysql:8.0.28
    container_name: mysql-springboot-container
    ports:
      - 3310:3306    
    volumes:
      - mysql-springboot-data:/var/lib/mysql
      - mysql-springboot-config-deamond:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      MYSQL_USER: hoangnd
      MYSQL_PASSWORD: Abc@123456789
      MYSQL_ROOT_PASSWORD: Abc@123456789
      MYSQL_DATABASE: StudentManagement
  springboot-docker-container:
    image: sunlight4d/springboot-docker:v1.0.0
    container_name: springboot-docker-container
    ports:
      - 8085:8083
    volumes:
      - ./:/app
    networks:
      - backend
#create network     
networks:
  backend:
    name: springboot-app-network
volumes:
  mysql-springboot-data:
  mysql-springboot-config-deamond: