spring:
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./h2db
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
    h2:
      console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      globally_quoted_identifiers: true
      globally_quoted_identifiers_skip_column_definitions: true
